name: turf_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0  # Use the latest version
  cupertino_icons: ^1.0.8

  # common
  get: ^4.6.6
  url_launcher: ^6.3.1
  intl: ^0.19.0
  http: ^1.2.2
  get_storage: ^2.1.1
  logger: ^2.4.0
  iconsax: ^0.0.8
  firebase_storage: ^12.3.6
  connectivity_plus: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  data_table_2: ^2.5.15
  smooth_page_indicator: ^1.2.0+3 #
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  firebase_auth: ^5.3.3
  flutter_native_splash: ^2.4.2
  readmore: ^3.0.0
  # firebase
  firebase_core: ^3.8.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  #
  web: ^1.1.0
  html: ^0.15.5
  fl_chart: ^0.69.0
  url_strategy: ^0.3.0
  universal_html: ^2.2.4
  path_provider: ^2.1.5
  table_calendar: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/icons/payment_methods/
    - assets/images/animations/
    - assets/images/content/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800